// <auto-generated />
using System;
using EjercicioMVCAndrade.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EjercicioMVCAndrade.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419231035_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EjercicioMVCAndrade.Models.Empleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Empleados", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            LastName = "Perez",
                            Name = "Juan"
                        },
                        new
                        {
                            id = 2,
                            LastName = "Gomez",
                            Name = "Maria"
                        },
                        new
                        {
                            id = 3,
                            LastName = "Lopez",
                            Name = "Carlos"
                        },
                        new
                        {
                            id = 4,
                            LastName = "Martinez",
                            Name = "Ana"
                        },
                        new
                        {
                            id = 5,
                            LastName = "Rodriguez",
                            Name = "Pedro"
                        });
                });

            modelBuilder.Entity("EjercicioMVCAndrade.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proyectos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Proyecto A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Proyecto B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Proyecto C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Proyecto D"
                        });
                });

            modelBuilder.Entity("EjercicioMVCAndrade.Models.Tareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoProgreso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechadeInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombredelatarea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer");

                    b.Property<double>("tiempoestimado")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpleadoId = 1,
                            EstadoProgreso = "Completado",
                            FechadeInicio = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Diseño de BD",
                            ProyectoId = 1,
                            tiempoestimado = 40.5
                        },
                        new
                        {
                            Id = 2,
                            EmpleadoId = 2,
                            EstadoProgreso = "En Progreso",
                            FechadeInicio = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Desarrollo Backend",
                            ProyectoId = 1,
                            tiempoestimado = 120.0
                        },
                        new
                        {
                            Id = 3,
                            EmpleadoId = 3,
                            EstadoProgreso = "En Progreso",
                            FechadeInicio = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Desarrollo Frontend",
                            ProyectoId = 1,
                            tiempoestimado = 100.0
                        },
                        new
                        {
                            Id = 4,
                            EmpleadoId = 4,
                            EstadoProgreso = "Pendiente",
                            FechadeInicio = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Pruebas",
                            ProyectoId = 1,
                            tiempoestimado = 30.0
                        },
                        new
                        {
                            Id = 5,
                            EmpleadoId = 5,
                            EstadoProgreso = "Completado",
                            FechadeInicio = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Análisis de Requisitos",
                            ProyectoId = 2,
                            tiempoestimado = 50.0
                        },
                        new
                        {
                            Id = 6,
                            EmpleadoId = 1,
                            EstadoProgreso = "Completado",
                            FechadeInicio = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Diseño de Interfaz",
                            ProyectoId = 2,
                            tiempoestimado = 60.0
                        },
                        new
                        {
                            Id = 7,
                            EmpleadoId = 2,
                            EstadoProgreso = "En Progreso",
                            FechadeInicio = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Implementación",
                            ProyectoId = 2,
                            tiempoestimado = 150.0
                        },
                        new
                        {
                            Id = 8,
                            EmpleadoId = 3,
                            EstadoProgreso = "Pendiente",
                            FechadeInicio = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Despliegue",
                            ProyectoId = 2,
                            tiempoestimado = 20.0
                        },
                        new
                        {
                            Id = 9,
                            EmpleadoId = 4,
                            EstadoProgreso = "Pendiente",
                            FechadeInicio = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Soporte",
                            ProyectoId = 2,
                            tiempoestimado = 40.0
                        },
                        new
                        {
                            Id = 10,
                            EmpleadoId = 5,
                            EstadoProgreso = "Pendiente",
                            FechadeInicio = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombredelatarea = "Documentación",
                            ProyectoId = 3,
                            tiempoestimado = 30.0
                        });
                });

            modelBuilder.Entity("EjercicioMVCAndrade.Models.Tareas", b =>
                {
                    b.HasOne("EjercicioMVCAndrade.Models.Empleado", "Empleado")
                        .WithMany("Tareas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EjercicioMVCAndrade.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("EjercicioMVCAndrade.Models.Empleado", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("EjercicioMVCAndrade.Models.Proyecto", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
